package com.sro.guessit

open class Constants {

    var gameList = listOf(
        "Among Us",
        "Mobile Legends: Bang Bang",
        "Free Fire",
        "Subway Surfers",
        "Clash of Clans",
        "Clash Royale",
        "Brawl Stars",
        "Freedom Fighters",
        "Roblox",
        "Alto's Odyssey",
        "Candy Crush Saga",
        "Garena Free Fire",
        "PUBG Mobile",
        "Fortnite",
        "Minecraft",
        "BTS World",
        "Pokémon GO",
        "Hearthstone",
        "Asphalt 9: Legends",
        "Call of Duty: Mobile",
        "Call of Duty",
        "Call of Duty 2",
        "Call of Duty 3",
        "Call of Duty 4: Modern Warfare",
        "Call of Duty: World at War",
        "Call of Duty: Modern Warfare 2",
        "Call of Duty: Black Ops",
        "Call of Duty: Modern Warfare 3",
        "Call of Duty: Black Ops II",
        "Call of Duty: Ghosts",
        "Call of Duty: Advanced Warfare",
        "Call of Duty: Black Ops III",
        "Call of Duty: Infinite Warfare",
        "Call of Duty: WWII",
        "Call of Duty: Black Ops 4",
        "Call of Duty: Modern Warfare (2019)",
        "Call of Duty: Warzone (standalone battle royale)",
        "Call of Duty: Black Ops Cold War",
        "Call of Duty: Vanguard",
        "Project IGI: I'm Going In (2000)",
        "Tekken",
        "The Witcher 4: Shadows of Nilfgaard",
        "CyberSprint",
        "Stellaris: Galactic Domination",
        "Quantum Nexus",
        "Celestial Crusaders",
        "Nebula Reckoning",
        "Interstellar Outlaws",
        "Galactic Odyssey",
        "Echoes of Eternity",
        "Quantum Breakout",
        "Starship Commanders",
        "Infinity Matrix",
        "Shadow of Nebula",
        "Gravity Rift",
        "Celestial Skirmish",
        "Solar Conquest",
        "Odyssey Zero",
        "Titan's Revenge",
        "Hypernova Raiders",
        "Quantum Shift",
        "Nebula Nexus",
        "Intergalactic Alliance",
        "Black Hole Havoc",
        "Quantum Flux",
        "Galactic Ascendancy",
        "Eternal Odyssey",
        "Cosmic Conquerors",
        "Nebula Nomads",
        "AstroStrike",
        "Odyssey: The Lost Frontier",
        "Quantum Quest",
        "Nebula Nomads",
        "Galactic Dominion",
        "Starlight Chronicles",
        "Titan's Wrath",
        "Quantum Warfare",
        "Celestial Clash",
        "Odyssey of Shadows",
        "Nebula Wars",
        "Galactic Genesis",
        "Infinity Reckoning",
        "Quantum Quasar",
        "Cosmic Frontiers",
        "Stellar Siege",
        "Nebula Nexus",
        "Solar Dynasty",
        "Quantum Cataclysm",
        "Celestial Battlegrounds",
        "Infinity Vanguard",
        "Galactic Reckoning",
        "Starship Expanse",
        "Quantum Legacy",
        "Nebula Nova",
        "Celestial Outlaws",
        "Eternal Frontier",
        "Stellar Vanguard",
        "Odyssey: Dark Horizon",
        "Quantum Storm",
        "Galactic Genesis",
        "Nebula Nomads",
        "Solar Ascendancy",
        "Celestial Conquest",
        "Infinity Ascendancy",
        "Quantum Echoes",
        "Starlight Raiders",
        "Odyssey Zero",
        "Nebula Dominion",
        "Galactic Nexus",
        "Celestial Skies",
        "Stellar Warriors",
        "Quantum Reckoning",
        "Cosmic Odyssey",
        "Eternal Nomads",
        "Nebula Nexus",
        "Solar Ascendancy",
        "Celestial Vanguard",
        "Quantum Expanse",
        "Galactic Cataclysm",
        "Starlight Clash",
        "Odyssey: Shadows of Infinity",
        "Nebula Nova",
        "Cosmic Dominion",
        "Quantum Nexus",
        "Celestial Exodus",
        "Stellar Reckoning",
        "Galactic Outlaws",
        "Infinity Nomads",
        "Nebula Ascendancy",
        "Quantum Dynasty",
        "Celestial Odyssey",
        "Odyssey: Celestial Frontier",
        "Cosmic Conquest",
        "Solar Vanguard",
        "Quantum Nexus",
        "Galactic Cataclysm",
        "Nebula Nomads",
        "Starlight Ascendancy",
        "Celestial Expanse",
        "Infinity Odyssey",
        "Stellar Dominion",
        "Quantum Genesis",
        "Nebula Ascendancy",
        "Solar Cataclysm",
        "Galactic Exodus",
        "Odyssey: The Final Frontier",
        "Celestial Nomads",
        "Cosmic Vanguard",
        "Quantum Reckoning",
        "Stellar Nexus",
        "Nebula Dynasty",
        "Infinity Conquest",
        "Solar Ascendancy",
        "Celestial Ascendancy",
        "Galactic Reckoning",
        "Odyssey: Celestial Exodus",
        "Quantum Dominion",
        "Nebula Ascendancy",
        "Cosmic Cataclysm",
        "Starlight Odyssey",
        "Celestial Genesis",
        "Stellar Ascendancy",
        "Quantum Exodus",
        "Galactic Nexus",
        "Nebula Cataclysm",
        "Infinity Conquest",
        "Solar Reckoning",
        "Odyssey: Celestial Vanguard",
        "Cosmic Exodus",
        "Quantum Dominion",
        "Celestial Ascendancy",
        "Galactic Odyssey",
        "Nebula Reckoning",
        "Infinity Cataclysm",
        "Solar Vanguard",
        "Quantum Nomads",
        "Starlight Conquest",
        "Odyssey: The Celestial Frontier",
        "Nebula Ascendancy",
        "Celestial Cataclysm",
        "Cosmic Odyssey",
        "Quantum Reckoning",
        "Galactic Vanguard",
        "Infinity Ascendancy",
        "Solar Nomads",
        "Stellar Exodus",
        "Nebula Conquest",
        "Celestial Reckoning",
        "Quantum Cataclysm",
        "Odyssey: Celestial Odyssey",
        "Galactic Cataclysm",
        "Infinity Exodus",
        "Solar Dominion",
        "Cosmic Ascendancy",
        "Quantum Vanguard",
        "Nebula Reckoning",
        "Celestial Ascendancy",
        "Starlight Genesis",
        "Odyssey: Infinity Nexus",
        "Galactic Conquest",
        "Cosmic Cataclysm",
        "Quantum Odyssey",
        "Nebula Dominion",
        "Stellar Ascendancy",
        "Celestial Reckoning",
        "Infinity Vanguard",
        "Solar Conquest",
        "Odyssey: The Cosmic Frontier",
        "Quantum Exodus",
        "Galactic Nomads",
        "Nebula Cataclysm",
        "Celestial Ascendancy",
        "Cosmic Nexus",
        "Starlight Cataclysm",
        "Quantum Vanguard",
        "Infinity Ascendancy",
        "Solar Odyssey",
        "Galactic Reckoning",
        "Nebula Conquest",
        "Celestial Dominion",
        "Odyssey: Celestial Cataclysm",
        "Cosmic Ascendancy",
        "Quantum Genesis",
        "Stellar Nomads",
        "Nebula Vanguard",
        "Infinity Odyssey",
        "Solar Cataclysm",
        "Galactic Ascendancy",
        "Starlight Dominion",
        "Quantum Reckoning",
        "Celestial Conquest",
        "Odyssey: Infinity Reckoning",
        "Cosmic Vanguard",
        "Nebula Cataclysm",
        "Stellar Ascendancy",
        "Quantum Exodus",
        "Infinity Conquest",
        "Solar Reckoning",
        "Galactic Nomads",
        "Starlight Odyssey",
        "Celestial Cataclysm",
        "Cosmic Odyssey",
        "Quantum Reckoning",
        "Nebula Ascendancy",
        "Infinity Ascendancy",
        "Solar Dominion",
        "Galactic Conquest",
        "Odyssey: Celestial Exodus",
        "Quantum Cataclysm",
        "Nebula Reckoning",
        "Celestial Ascendancy",
        "Cosmic Genesis",
        "Starlight Conquest",
        "Infinity Exodus",
        "Solar Vanguard",
        "Quantum Nomads",
        "Galactic Odyssey",
        "Nebula Ascendancy",
        "Celestial Reckoning",
        "Stellar Cataclysm",
        "Odyssey: Infinity Vanguard",
        "Cosmic Ascendancy",
        "Quantum Reckoning",
        "Galactic Conquest",
        "Nebula Dominion",
        "Solar Ascendancy",
        "Celestial Odyssey",
        "Infinity Cataclysm",
        "Starlight Genesis",
        "Quantum Nexus",
        "Odyssey: The Celestial Frontier",
        "Nebula Reckoning",
        "Cosmic Cataclysm",
        "Solar Vanguard",
        "Quantum Odyssey",
        "Celestial Ascendancy",
        "Grand Theft Auto",
        "Grand Theft Auto: London, 1969",
        "Grand Theft Auto: London, 1961",
        "Grand Theft Auto 2",
        "Grand Theft Auto III",
        "Grand Theft Auto Advance",
        "Grand Theft Auto: Liberty City Stories",
        "Grand Theft Auto: Vice City Stories",
        "Grand Theft Auto IV",
        "Grand Theft Auto: The Lost and Damned",
        "Grand Theft Auto: Chinatown Wars",
        "Grand Theft Auto: The Ballad of Gay Tony",
        "Grand Theft Auto V",
        "Diablo II",
        "The Sims",
        "Deus Ex",
        "Counter-Strike",
        "Baldur's Gate II: Shadows of Amn",
        "Max Payne",
        "Return to Castle Wolfenstein",
        "Grand Theft Auto III",
        "Civilization III",
        "Halo: Combat Evolved",
        "Warcraft III: Reign of Chaos",
        "Battlefield 1942",
        "Morrowind (The Elder Scrolls III)",
        "Neverwinter Nights",
        "Medal of Honor: Allied Assault",
        "Call of Duty",
        "Star Wars: Knights of the Old Republic",
        "The Sims 2",
        "Command & Conquer: Generals",
        "Freelancer",
        "Half Life 2",
        "World of Warcraft",
        "Doom 3",
        "Far Cry",
        "Rome: Total War",
        "F.E.A.R.",
        "Civilization IV",
        "Battlefield 2",
        "Quake 4",
        "Age of Empires III",
        "The Elder Scrolls IV: Oblivion",
        "Company of Heroes",
        "Gears of War",
        "Gothic 3",
        "Rainbow Six: Vegas",
        "Crysis",
        "Team Fortress 2",
        "BioShock",
        "The Witcher",
        "Call of Duty 4: Modern Warfare",
        "Fallout 3",
        "Left 4 Dead",
        "Grand Theft Auto IV",
        "World of Goo",
        "Far Cry 2",
        "Dragon Age: Origins",
        "Batman: Arkham Asylum",
        "Borderlands",
        "Assassin's Creed II",
        "Left 4 Dead 2",
        "StarCraft II: Wings of Liberty",
        "Fallout: New Vegas",
        "Mass Effect 2",
        "Civilization V",
        "Minecraft",
        "The Elder Scrolls V: Skyrim",
        "Battlefield 3",
        "Portal 2",
        "Dark Souls",
        "Deus Ex: Human Revolution",
        "Diablo III",
        "Far Cry 3",
        "XCOM: Enemy Unknown",
        "Guild Wars 2",
        "Dishonored",
        "Bioshock Infinite",
        "Tomb Raider",
        "Grand Theft Auto V",
        "The Witcher 3: Wild Hunt",
        "Battlefield 4",
        "Middle-earth: Shadow of Mordor",
        "Dragon Age: Inquisition",
        "Dark Souls II",
        "Civilization: Beyond Earth",
        "Alien: Isolation",
        "The Witcher 3: Wild Hunt",
        "Fallout 4",
        "Metal Gear Solid V: The Phantom Pain",
        "Rocket League",
        "Cities: Skylines",
        "Call of Duty: Modern Warfare",
        "Freedom Fighters",
        "Grand Theft Auto V",
        "Super Mario Bros",
        "Battlefield 4",
        "Fall Guys",
        "Far Cry 3",
        "Bounce",
        "Subway Surfers",
        "Among Us",
        "Tomb Raider",
        "Temple Run",
        "Minecraft",
        "IGI 2 Covert Strike",
        "Cricket 07",
        "Fallout: New Vegas",
        "Hill Climb Racing",
        "Plants vs Zombies",
        "8 Ball Pool",
        "Fifa",
        "Fortnite",
        "Candy Crush Saga",
        "CYBERPUNK 2077",
        "Valorant",
        "Dota 2",
        "Apex Legends",
        "Hitman",
        "Resident Evil 4",
        "It Takes Two",
        "Scarlet Nexus",
        "Clash Royale",
        "Roblox",
        "Alto's Odyssey",
        "Clash of Clans",
        "Idle Miner Tycoon",
        "Red Ball 4",
        "GTA San Andreas",
        "Tekken",
        "GTA Vice City",
        "The Sims",
        "Wolfenstein The New Order",
        "Microsoft Flight Simulator",
        "Red Dead Redemption",
        "The Last of Us",
        "God of war",
        "The Witcher",
        "Mass Effect 1",
        "Metal Gear Solid 2: Sons of liberty",
        "Grand Theft Auto IV",
        "Alan Wake 2",
        "Elden Ring",
        "Uncharted 2: Among Thieves",
    )
}